# -*- coding: utf-8 -*-
"""tax-day1-ingggo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRqfT_vC2zoGKv6lHaAb1GJFFBpAeJcx

#파이썬 첫번째

##코드(더하기)

###서브서브세션
"""

1+1

"""#파이썬 두번째"""

2*5

"""#파이썬 세번째"""

print("Hello, world!")

name = "홍길동"
age = 25
height = 175.5

print(name, "님의 나이는", age, "살입니다.")

a = 10
b = 3

print("더하기:", a + b)
print("빼기:", a - b)
print("곱하기:", a * b)
print("나누기:", a / b)
print("나머지:", a % b)

score = 85

if score >= 90:
    print("A 학점")
elif score >= 80:
    print("B 학점")
else:
    print("C 학점 이하")

score = 60

if score >= 90:
    print("A 학점")
elif score >= 80:
    print("B 학점")
else:
    print("C 학점 이하")

# for문
for i in range(5):
    print("반복:", i)

# while문
count = 0
while count < 3:
    print("Hello!")
    count += 1

